" Display line numbers
set number

" Enable syntax highlighting
syntax on

" Use UTF-8
set encoding=utf-8

" Show a few lines of context around the cursor when scrolling
set scrolloff=5

" Highlight current line
set cursorline

" Visual autocomplete for command menu
set wildmenu

" Automatically indent when adding a curly bracket, etc..
set smartindent

" Tabs are 4 columns wide. Each indentation level is 4 spaces
set tabstop=4      " number of visual spaces per TAB
set softtabstop=4  " number of spaces inserted when hitting TAB
set shiftwidth=4   " number of spaces per (auto)indent (>>, <<, etc..)
set expandtab      " turns TAB into spaces

" Back to normal mode
imap jk <esc>
vmap jk <esc>

" Status line
set laststatus=2

" Milliseconds of inactivity after which the swap file will be written to disk.
" This also controls the update frequency of vim-gitgutter
set updatetime=100

" Open the new window below the current one for horizontal splits
set splitbelow
" Open the new window to the right of the current one for vertical splits
set splitright

" Make preview window height half the size of the current window
exec 'set previewheight=' . string(winheight(0)/2)

" Install vim-plug automatically
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugins
call plug#begin('~/.vim/plugged')

Plug 'danilo-augusto/vim-afterglow'
Plug 'editorconfig/editorconfig-vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'kongo2002/fsharp-vim'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'jiangmiao/auto-pairs'
Plug 'dart-lang/dart-vim-plugin'
Plug 'lervag/vimtex'
Plug 'digitaltoad/vim-pug'

" Snippet plugin with dependencies
Plug 'marcweber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
Plug 'garbas/vim-snipmate'

Plug 'w0rp/ale'
Plug 'natebosch/vim-lsc'

let g:lsc_server_commands = {'dart': 'dart_language_server'}
" Automatically close the documentation window
autocmd CompleteDone * silent! pclose

let g:snipMate = {}
let g:snipMate.snippet_version = 1

call plug#end()

" SublimeText color scheme
colorscheme afterglow

" Open terminal window
map <F12> <Esc>:exec 'term ++rows=' . string(&lines * 0.3)<CR><C-W>:set winfixheight<CR>

" Send selection to fsharpi (assumes that fsharpi is running in a terminal
" window located below the current one)
autocmd FileType fsharp vmap <C-M> "+y<C-W>j<C-W>"+;;<CR>

" Disable arrow keys
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>

" Move/swap lines or selections
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
inoremap <C-j> <Esc>:m .+1<CR>==gi
inoremap <C-k> <Esc>:m .-2<CR>==gi
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv

